### PR TITLE
GitHub action publish

### LINKED ISSUE #12: FR: please co-publish on Open VSX Registry
The [Open VSX Registry](https://open-vsx.org/?search=gettext) does not include any extensions yet. It is the default extension provider of free "vscode" builds and it would be good to find this extension there, too.

Details on the publishing can be found at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions.

### LINKED ISSUE #23: https://open-vsx.org/ Did not find it, VSCodium could not be installed
https://open-vsx.org
Did not find it, VSCodium could not be installed
没有发现它，无法安装

### PR DESCRIPTION
**Pull request by MrOrz**
Try implementing Github action for deployment as mentioned by @GitMensch in #12

- [x] Fix CI
- [x] Try using older VS code engine to address https://github.com/MrOrz/vscode-gettext/pull/26#pullrequestreview-1145228967

### CODE REVIEW

**Comment by MrOrz** [comment]
Seems that I need to remove the outdated vscode package, or postinstall will fail https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode

**Comment by GitMensch** [comment]
Yes, sounds reasonable.
Note: please don't increase the actual type version as otherwise the extension won't work on "old" installations of vscode any more... oops, already done in #26 so will comment there.

**Comment by GitMensch** [comment]
That goes nicely!

You may want to split the "test" part into an own action which can then also be executed on PR and either have the other separate or include that step.

**Comment by MrOrz** [comment]
@GitMensch Thanks for the timely review!

It is a great idea to rewrite testing part into a reusable workflow or an action.

But to consider my personal workflow, I want to trigger publish using Github Release, so that I won't forget writing release notes. As triggering publish becomes a manual step, by the time I create a new Github Release, the CI workflow on master branch should have finished. In this case, I think we don't need to repeat the test on publish :)

**Comment by MrOrz** [comment]
Not sure why open-vsx does not update: https://open-vsx.org/extension/mrorz/language-gettext
Under the same Github action, VS market place does update https://marketplace.visualstudio.com/items?itemName=mrorz.language-gettext

**Pull request merged**
