### PR TITLE
Show the output of `msgfmt --statistics` in the status bar

### LINKED ISSUE #4: Stats in status bar
- msgid count
- translated msgstr count
- fuzzy count
- % translated
- % fuzzy

### PR DESCRIPTION
**Pull request by toku-sa-n**
Partially fixes #4. This prints the counts of total, untranslated, and fuzzy messages.

### CODE REVIEW

**Comment by MrOrz** [comment]
Thanks for adding this neat feature! I somehow cannot verify this feature even though I have `msgfmt` installed.
截圖 2024-02-13 下午11 14 19

I think it would be helpful if we can show some debug log in the output tab in the bottom panel when the `updateStsatusBarmItem` (or `updateStatusBarItem`?) cannot show status.

**Comment by toku-sa-n** [comment]
Thank you for trying! I temporarily added a logging feature to the debug console. Could you retry it?
Also, I'm considering telling users the error via some information box and will implement it later.

**Comment by toku-sa-n** [comment]
By the way, here is a working screenshot. You can see "3067 個の翻訳メッセージ, 4685 個のあいまいな翻訳, 2624 個の未訳のメッセージ." (3067 messages, 4685 fuzzy translations, 2624 untranslated messages.) at the bottom.
14-02-2024_09:26:38_screenshot

**Comment by MrOrz** [comment]
Thanks for the modification! I can read the error messages in the debug console:
截圖 2024-02-15 上午10 29 02
Seems that the shell environment in VSCode does not pick up `msgfmt` installed through Homebrew. 

The error is also shown here in the status bar:
截圖 2024-02-15 上午10 29 42

In the scenario where `msgfmt` is not found the environment, I think it would be better if we just `console.error` without showing it in the status bar. It will be good to merge when the error message does not take up space in the status bar.

**Comment by toku-sa-n** [comment]
Fixed it. Could you try it again?

**Review by MrOrz — APPROVED** [review]
Thanks for the fix! The error that msgfmt is not found is shown in Debug Console as expected, without displaying the error on status bar. It's now good to go 👍🏻

**Comment by GitMensch** [comment]
Even when this is after the fact now - can you please update CHANGELOG.md so people have a clue what's changed between the versions?

**Comment by MrOrz** [comment]
I thought it's already included in https://github.com/MrOrz/vscode-gettext/releases

And CHANGELOG.md also points the readers there

**Comment by MrOrz** [comment]
Sorry it didn't, let me check why

Edit: I forgot to publish the change. I have just bumped the version (using my another Github account) and published a new version; change log already included in https://github.com/MrOrz/vscode-gettext/releases .

**Comment by GitMensch** [comment]
I see.

> Changes beyond 0.2.0 please see Github releases https://github.com/MrOrz/vscode-gettext/releases

The issue: this is not rendered in the market places or in the clients using this extension (for vscode: go to extensions settings, then to changes) and doesn't work when working offline either :-/

**Pull request merged**
